### PR TITLE
Increase default heap size for 64-bit build

### LINKED ISSUE #1633: Possible Z_Malloc error on playing demo under x64 build
### Background

Version of Chocolate Doom: built from latest code on GitHub. Both executable builds were made by made using MSYS environment (GCC 13.2.0, "Release" type, x86 and x64 respectively).

Operating System and version: Windows 11, latest 23H2

Any loaded WADs and mods (please include full command line): `-file av.wad -timedemo avm62402.lmp -nodraw`

### Bug description

Observed behavior:

This is memory related stuff which I'm not able to understand properly, so @rfomin suggested to write it "as is".

I have spotted that playing [6 hour demo](https://www.dsdarchive.com/files/demos/av/61064/avm62402.zip) of Alien Vendetta is causing silent crash on **x64** build of Chocolate Doom after entering MAP20 (Misri Halek). It's not exactly "silent", it's just prints "Warning: recursive call to I_Error detected." in console and quits. 

Command line:
`chocolate-doom.exe -file AV.WAD -timedemo avm62402.lmp -nodraw`

<hr>

In **x86** build it plays normally without any errors and able to finish demo just normally, showing "Timed 821041 gametics in 539 realtics..."

Command line (same):
`chocolate-doom.exe -file AV.WAD -timedemo avm62402.lmp -nodraw`

<hr size>

In **DOS** Doom II v1.9 executable, it gives following error message:
image

Command line:
`doom2.exe -file AV.WAD -timedemo avm62402 -nodraw`

_Please note: it may take up to 2-3 minutes to reach MAP20, even by using 100% CPU cycles!_

<hr>

In theory, this can be related to triggering SPECHITS overflow, here's what I can see in console prints by using CRL (same overflows handling as in Crispy Doom):

<details>

```
P_SetupLevel: MAP01, loaded in 8 ms.
P_SetupLevel: MAP02, loaded in 11 ms.
P_SetupLevel: MAP03, loaded in 9 ms.
P_SetupLevel: MAP04, loaded in 22 ms.
P_SetupLevel: MAP05, loaded in 6 ms.
PIT_CheckLine: Triggered SPECHITS overflow!
P_SetupLevel: MAP06, loaded in 11 ms.
P_SetupLevel: MAP07, loaded in 12 ms.
P_SetupLevel: MAP08, loaded in 5 ms.
P_SetupLevel: MAP09, loaded in 5 ms.
P_SetupLevel: MAP10, loaded in 2 ms.
P_SetupLevel: MAP11, loaded in 22 ms.
P_SetupLevel: MAP12, loaded in 12 ms.
P_SetupLevel: MAP13, loaded in 6 ms.
P_SetupLevel: MAP14, loaded in 5 ms.
P_SetupLevel: MAP15, loaded in 8 ms.
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
PIT_CheckLine: Triggered SPECHITS overflow!
P_SetupLevel: MAP31, loaded in 18 ms.
P_SetupLevel: MAP32, loaded in 6 ms.
P_SetupLevel: MAP16, loaded in 4 ms.
P_SetupLevel: MAP17, loaded in 6 ms.
P_SetupLevel: MAP18, loaded in 7 ms.
P_SetupLevel: MAP19, loaded in 8 ms.
P_SetupLevel: MAP20,   zone memory: 000001e5901f7040, 10 MiB allocated for zone. // [JN] Note: this by using prevention of Z_Malloc errors from Crispy Doom by increasing zone size when it's full. Without prevention it will crash same way as x64 build of Chocolate Doom.
loaded in 6 ms.
P_SetupLevel: MAP21, loaded in 5 ms.
```
</details>

<hr>

Expected behavior:

Not sure what is correct behavior in this case. Turns out, both DOS and x64 version are crashing in slightly different ways, while x86 is able to play demo normally. 🤔

### PR DESCRIPTION
**Pull request by rfomin**
Because of the 8-byte pointer size in a 64-bit build, the default heap size (16 Mbytes) is insufficient compared to a 32-bit build. For example, the Alien Vendetta [avm62402.lmp](https://www.dsdarchive.com/files/demos/av/61064/avm62402.zip) demo completes successfully in a 32-bit build but in a 64-bit build it terminates with an out of memory error. Hence increase of the heap size twice for consistency with a 32-bit build.

Fix #1633, thanks to @JNechaevsky for the bug report.

### CODE REVIEW

File: src/i_system.c [hunk 1]
```diff
@@ -49,7 +49,11 @@
 #include "w_wad.h"
 #include "z_zone.h"
 
-#define DEFAULT_RAM 16 /* MiB */
+#if SIZEOF_VOID_P == 8
```
Comment (turol) [inline src/i_system.c:52]: 1. There's no comment explaining why.
2. Why the complicated build system and preprocessor trickery? There's only one user of `DEFAULT_RAM`, you can just as well put this there and don't have to change the build system.

**Review by turol — CHANGES_REQUESTED** [review]

File: src/i_system.c (hunk 1 above)
Comment (fabiangreffrath) [reply src/i_system.c:52]: I have to agree with @turol here. This change is too much to determine a single value that is used only once.

Comment (rfomin) [reply src/i_system.c]: Fixed in https://github.com/chocolate-doom/chocolate-doom/pull/1635/commits/4545a70dd14d941c0a570f12854e313ba73b483c

**Review by fabiangreffrath — APPROVED** [review]

**Review by turol — APPROVED** [review]
