### PR TITLE
Gracefully error out when player starts are missing

### LINKED ISSUE #1049: Segfault when loading map with no player 1 start
[https://github.com/fabiangreffrath/crispy-doom/issues/315](https://github.com/fabiangreffrath/crispy-doom/issues/315)

### PR DESCRIPTION
**Pull request by mfrancis95**
Fixes #1049, including the multiplayer case.

### CODE REVIEW

File: src/doom/p_setup.c [hunk 1]
```diff
@@ -389,6 +390,11 @@ void P_LoadThings (int lump)
 	P_SpawnMapThing(&spawnthing);
     }
 
+    if (!deathmatch)
```
Comment (chungy) [inline src/doom/p_setup.c]: Though vanilla code is inconsistent, we would prefer that you put braces around all these `if` and `for` statements.

Comment (mfrancis95) [reply src/doom/p_setup.c]: Done.

**Comment by chungy** [comment]
Thanks for this!
