### PR TITLE
hexen: Fix P_LookForPlayers desync

### LINKED ISSUE #1663: Hexen: possible desync on multi-level demo (and now single map demo)
The demo in question is https://dsdarchive.com/files/demos/hexen/62317/hxAllf646.zip

At about 2:30, the player uses a porkalator to turn a few ettins into pigs. 

In hexenp.exe and dsda-doom, one pig wanders towards the player, who uses it to glitch through the wall, and is then able to complete the level early.

In Chocolate Hexen, the pig takes a slightly different path, and as such the player isn't lined up properly and the demo desyncs. `-demoextend` is required, and `-longtics` seems to make no difference.

Tested in Chocolate Doom 3.0.1 as well as latest git version, on Linux 64-bit.

### PR DESCRIPTION
**Pull request by mikeday0**
The vanilla behavior results in a lock-up. Let's error out instead. Fixes #1663.

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
Very good solution, thank you!

File: src/hexen/p_enemy.c [hunk 1]
```diff
@@ -528,25 +528,29 @@ boolean P_LookForPlayers(mobj_t * actor, boolean allaround)
     player_t *player;
     angle_t an;
     fixed_t dist;
+    int i = 0; // For breaking vanilla infinite loop.
```
Comment (turol) [inline src/hexen/p_enemy.c:531]: A more descriptive name would be better. It's not really a loop index since it's reset during the loop.

File: src/hexen/p_enemy.c [hunk 2]
```diff
@@ -528,25 +528,29 @@ boolean P_LookForPlayers(mobj_t * actor, boolean allaround)
...
-    stop = (actor->lastlook + maxplayers - 1) % maxplayers;
-    for (;; actor->lastlook = (actor->lastlook + 1) % maxplayers)
+    stop = (actor->lastlook - 1) & 3;
+    for (;; actor->lastlook = (actor->lastlook + 1) & 3)
     {
         if (!playeringame[actor->lastlook])
+        {
+            // In vanilla, an infinite loop can occur here if there are > 4
+            // players and players 0 - 3 all quit the game. Error out instead.
+            if (i++ == 4)
```
Comment (turol) [inline src/hexen/p_enemy.c:546]: Is the value 4 correct here? What happens if we start with 8 players and then players 7 and 0-2 quit?

I consider increment as part of an expression a bad habit. It always requires careful thinking of pre- vs post-increment value. It should be its own statement.

File: src/hexen/p_enemy.c [hunk 3]
```diff
@@ -528,25 +528,29 @@ boolean P_LookForPlayers(mobj_t * actor, boolean allaround)
...
+            {
+                I_Error("P_LookForPlayers: No player 1 - 4.\n");
+            }
             continue;
+        }
+
+        i = 0; // Found a player.
```
Comment (turol) [inline src/hexen/p_enemy.c:553]: There are more `continue`s below. Is it possible for them to trigger the infinite loop if `i` is reset?

File: src/hexen/p_enemy.c [hunk 4]
```diff
@@ -528,25 +528,29 @@ boolean P_LookForPlayers(mobj_t * actor, boolean allaround)
...
     fixed_t dist;
+    int i = 0; // For breaking vanilla infinite loop.
 
     if (!netgame && players[0].health <= 0)
     {                           // Single player game and player is dead, look for monsters
         return (P_LookForMonsters(actor));
     }
     c = 0;
 
-    // NOTE: This behavior has been changed from the Vanilla behavior, where
```
Comment (turol) [inline src/hexen/p_enemy.c:538]: There should be a warning comment here that `3` can't be changed to `maxplayers` or desyncs will result.

**Review by turol — CHANGES_REQUESTED** [review]
The commit message should say that this is a revert and mention the reverted commit.

The original commit applies the same change to Strife, should that also be reverted?

File: src/hexen/p_enemy.c (hunk 3 above)
Comment (mikeday0) [reply src/hexen/p_enemy.c:553]: No. As long as there at least one valid player 0 - 3, the function will eventually exit via the `if (c++ == 2 || ...)` condition.

**Comment by kitchen-ace** [comment]
@turol 
>The original commit applies the same change to Strife, should that also be reverted?

Proper demos are effectively impossible to record in vanilla Strife -- as soon as you enter a dialogue menu with anyone it's the same as bringing up a menu with ESC, which will cause a desync in vanilla. It's theoretically possible to record some individual levels without triggering dialogue but I don't know that any such demos exist; dsdarchive doesn't have any.

**Comment by ceski-1** [comment]
> Proper demos are effectively impossible to record in vanilla Strife

I believe multiplayer demos still work fine in Strife.

**Comment by ceski-1** [comment]
>  as soon as you enter a dialogue menu with anyone it's the same as bringing up a menu with ESC, which will cause a desync in vanilla

The dialogue system is disabled in Strife multiplayer to prevent this from happening.

**Comment by kitchen-ace** [comment]
>I believe multiplayer demos still work fine in Strife.

>The dialogue system is disabled in Strife multiplayer to prevent this from happening.

Oh interesting. Does the game allow full progress without dialogue?

I wonder, are there any chocolate-compatible Strife wads?

**Comment by ceski-1** [comment]
> Oh interesting. Does the game allow full progress without dialogue?

I believe dialogue choices are required for progress.

> I wonder, are there any chocolate-compatible Strife wads?

Yes, a recent example: https://www.doomworld.com/forum/topic/132102-strife-big-sehacked-fueled-vanilla-map-idgames/

File: src/hexen/p_enemy.c (hunk 2 above)
Comment (fabiangreffrath) [reply src/hexen/p_enemy.c:546]: > Is the value 4 correct here? What happens if we start with 8 players and then players 7 and 0-2 quit?

Yes, `4` is correct. Due to `actor->lastlook = (actor->lastlook + 1) & 3` we know that if the loop was repeated four times, it will continue repeating forever.

> I consider increment as part of an expression a bad habit. It always requires careful thinking of pre- vs post-increment value. It should be its own statement.

The same is done in the Vanilla code just a few lines later.

File: src/hexen/p_enemy.c (hunk 1 above)
Comment (fabiangreffrath) [reply src/hexen/p_enemy.c:531]: It never even claimed to be a loop index. In fact it's a loop counter. But admittedly, `i` is probably the most generic name of all.

**Comment by mikeday0** [comment]
@turol I've implemented your suggestions. Let me know if anything can be improved.

File: src/hexen/p_enemy.c (hunk 3 above)
Comment (turol) [reply src/hexen/p_enemy.c]: I'm still not entirely sure this can't infinite loop but I'll take your word for it.

**Review by turol — APPROVED** [review]
