### PR TITLE
v_video.c: Enhance V_DrawMouseSpeedBox in non-acceleration cases

### LINKED ISSUE #791: Setup: crash testing mouse when "Acceleration Threshold" is zero
Cause is this line in `v_video.c`:
```
// Calculate line length

linelen = (original_speed * redline_x) / mouse_threshold;
```
Not sure if we should disallow zero threshold or if the thermometer should act differently.

### PR DESCRIPTION
**Pull request by CapnClever**
Resolves #791.

EDIT: Functionality has changed: see later comments for explanation. Original description below:

> Since the box isn't drawn when acceleration is irrelevant to the thermometer, I went with the simplest solution and added `mouse_threshold == 0` to the no-draw condition.

### CODE REVIEW

**Comment by fragglet** [comment]
Your fix looks fine, but it seems a bit like surprising behavior that there are config settings that hide the calibration box. I wonder if we can change it so that it's still shown in all circumstances?

**Comment by CapnClever** [comment]
I was actually working on such changes when I noticed the disabling condition, so I went with the simpler solution. I don't mind expanding the calibration box instead of suppressing it, though.

My original plan in the acceleration-less case was to make the mouse speed equal to the number of line-pixels. Thinking about it now, it's rather easy to hit this upper bound, so maybe whenever the value peaks (i.e., hits the top of the box) the thermometer's readout is halved to compensate: that way even a mouse with high DPI would get a reasonable understanding of relative speed.

**Comment by CapnClever** [comment]
Changed functionality as per my suggestions. In addition, I included a horizontal bar (yellow in color) whenever the line resolution changes, so that a player can understand and track these changes easily.

File: src/v_video.c [hunk 1]
```diff
@@ -948,9 +970,21 @@ void V_DrawMouseSpeedBox(int speed)
...
 
-    // Draw red line
-
-    V_DrawVertLine(box_x + redline_x, box_y + 1,
-                 MOUSE_SPEED_BOX_HEIGHT - 2, red);
+    if (draw_acceleration)
+    {
+        // Draw acceleration threshold line
+        V_DrawVertLine(box_x + redline_x, box_y + 1,
+                    MOUSE_SPEED_BOX_HEIGHT - 2, red);
```
Comment (fragglet) [inline src/v_video.c]: Please fix alignment of this line.

**Comment by CapnClever** [comment]
Fixed (force-pushed the change); I saw other lines in that function that could have improved alignments and adjusted them as well.

**Comment by fragglet** [comment]
Thanks!
