### PR TITLE
Disable SDL Mixer Windows native midi

### LINKED ISSUE #1729: Side effects when changing Music-Volume with GUS emulator (w/o gus patches)
### Background

**Version of Chocolate Doom:** 3.1.0

**Operating System and version:** Windows 10

**Game:** Doom, Heretic, Hexen, Strife

**Any loaded WADs and mods (please include full command line):** - 

**### Bug description:**
1. Select GUS Emulator in Audio Setup (without a path set)
2. Reduce / Turn off Music Volume in-game, keep SFX Volume to full
3. Select e. g. OPL or Native MIDI in Audio Setup
4. Start the game and switch both SFX and Music to full

**Observed behavior:**

Both SFX and Music Audio remain either off / or are reduced by the amount in step 2) when GUS Emulator was active. 

**Expected behavior:**

SFX and Music Settings should work normally when switching from GUS to something else, no hidden offset or disabling.

### PR DESCRIPTION
**Pull request by mikeday0**
Fixes #1729. I don't see any downside to this since we handle native midi on Windows ourselves.

### CODE REVIEW

File: src/i_sdlmusic.c [hunk 1]
```diff
@@ -208,6 +210,12 @@ static boolean I_SDL_InitMusic(void)
         }
     }
 
+    #ifdef _WIN32
+    // Never let SDL Mixer use native midi on Windows. Avoids SDL Mixer bug
+    // where music volume affects global application volume.
+    putenv(sdl_mixer_disable_nativemidi);
```
Comment (fabiangreffrath) [inline src/i_sdlmusic.c:216]: You could just pass the string directly to `putenv()` here. This will save you from two issues: First, you do not need to add a string literal to global context. And second, you won't forget to embrace that variable in `#ifdef _WIN32`. 😉

Comment (fabiangreffrath) [reply src/i_sdlmusic.c:216]: Oh wow. Yes, "silliness" describes it best.

Anyway, please add the `#ifdef _WIN32` check around that variable then.

Comment (mikeday0) [reply src/i_sdlmusic.c:216]: I'll add a comment as well.

**Review by fabiangreffrath — APPROVED** [review]
Looks good, thank you! And pardon my confusion regarding `putenv()` handling. 😉

**Comment by mikeday0** [comment]
> Looks good, thank you! And pardon my confusion regarding `putenv()` handling. 😉

Looks like there's a `SDL_setenv()` available. (Thanks @bradharding for the tip!) I haven't investigated it, but maybe it would be better to swap out all the `putenv()` calls in the code for this? A task for another time I suppose.

**Comment by rfomin** [comment]
> > Looks good, thank you! And pardon my confusion regarding `putenv()` handling. 😉
> 
> Looks like there's a `SDL_setenv()` available. (Thanks @bradharding for the tip!) I haven't investigated it, but maybe it would be better to swap out all the `putenv()` calls in the code for this? A task for another time I suppose.

`SDL_setenv()` is undocumented. It's unlikely that they'll change the SDL2 API at this point, but I still think `putenv()` is good enough. Regular `setenv()` is not available on Windows.
